<a href="https://colab.research.google.com/github/tornikeo/deep_neural_networks_with_pytorch/blob/master/torch_tensors_in_1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

import torch
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
torch.__version__

'1.3.1'

In [0]:
# Plot vecotrs, please keep the parameters in the same length
# @param: Vectors = [{"vector": vector variable, "name": name of vector, "color": color of the vector on diagram}]

def plotVec(vectors):
    ax = plt.axes()

    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

In [18]:
ints_to_tensor = torch.tensor([0,1,2,3,4])
ints_to_tensor.dtype, ints_to_tensor.type()

(torch.int64, 'torch.LongTensor')

In [19]:
type(ints_to_tensor)

torch.Tensor

In [23]:
list_floats = [0.2, .3, .4, 1.5]

floats_int_tensor=torch.tensor(list_floats, dtype=torch.int64)
floats_int_tensor.dtype, floats_int_tensor.numpy()

(torch.int64, array([0, 0, 0, 1]))

In [24]:
new_float_tensor = torch.FloatTensor([0,1,2,3,4,5])
new_float_tensor.numpy()

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [26]:
new_float_tensor.view(-1,1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])

From Pandas to torch tensor

In [27]:
pandas_series = pd.Series([.1,2,.3,10.1])
new_tensor = torch.from_numpy(pandas_series.values)
new_tensor

tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)

Converting from regular tensors to tensor object with 1 row and 5 columns

In [0]:
regular_tensor = torch.tensor([1,2,3,4,5])
new_tensor = regular_tensor.view(1,5)